import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Nav from './components/nav'
import "./globals.css";
import { Context } from "./_context/Context";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <Context>
      <html lang="en">
          
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased flex items-center flex-col gap-8 h-screen bg-black text-white`}
            >
              <Nav/>
              <div className="flex flex-col items-center justify-center h-screen">{children}</div>
            </body>
          
        
      </html>
    </Context>
  );
}
